"""First-layer public facade for nominal rates-domain objects."""

from __future__ import annotations

from fuggers_py._core import OptionType, PayReceive
from fuggers_py._pricers.rates.futures import cheapest_to_deliver, conversion_factor, invoice_amount
from fuggers_py._pricers.rates.options import BachelierPricer, Black76Pricer, HullWhiteOptionPricer
from fuggers_py._pricers.rates.risk import key_rate_risk, swap_dv01

from .indices import (
    ArrearConvention,
    BondIndex,
    IndexConventions,
    IndexFixing,
    IndexFixingStore,
    IndexSource,
    LockoutDays,
    LookbackDays,
    ObservationShiftType,
    OvernightCompounding,
    PublicationTime,
    ShiftType,
)
from .pricing import (
    AssetSwapBreakdown,
    AssetSwapPricer,
    AssetSwapPricingResult,
    BasisSwapPricer,
    BasisSwapPricingResult,
    CrossCurrencyBasisSwapPricer,
    CrossCurrencyBasisSwapPricingResult,
    FraPricer,
    FraPricingResult,
    SwapPricer,
    SwapPricingResult,
)
from .products import (
    AccrualPeriod,
    AssetSwap,
    BasisSwap,
    CapFloor,
    CapFloorType,
    CrossCurrencyBasisSwap,
    DeliverableBasket,
    DeliverableBond,
    FixedFloatSwap,
    FixedLegSpec,
    FloatingLegSpec,
    ForwardRateAgreement,
    Fra,
    FuturesOption,
    GovernmentBondFuture,
    HasExpiry,
    HasOptionType,
    HasUnderlyingInstrument,
    InterestRateSwap,
    Ois,
    OvernightIndexedSwap,
    SameCurrencyBasisSwap,
    ScheduleDefinition,
    Swaption,
)
from .quotes import BasisSwapQuote, BondFutureQuote, FxForwardQuote, SwapQuote

__all__ = [
    "AccrualPeriod",
    "ArrearConvention",
    "AssetSwap",
    "AssetSwapBreakdown",
    "AssetSwapPricer",
    "AssetSwapPricingResult",
    "BachelierPricer",
    "BasisSwap",
    "BasisSwapPricer",
    "BasisSwapPricingResult",
    "BasisSwapQuote",
    "Black76Pricer",
    "BondFutureQuote",
    "BondIndex",
    "CapFloor",
    "CapFloorType",
    "CrossCurrencyBasisSwap",
    "CrossCurrencyBasisSwapPricer",
    "CrossCurrencyBasisSwapPricingResult",
    "DeliverableBasket",
    "DeliverableBond",
    "FixedFloatSwap",
    "FixedLegSpec",
    "FloatingLegSpec",
    "ForwardRateAgreement",
    "Fra",
    "FraPricer",
    "FraPricingResult",
    "FuturesOption",
    "FxForwardQuote",
    "GovernmentBondFuture",
    "HasExpiry",
    "HasOptionType",
    "HasUnderlyingInstrument",
    "HullWhiteOptionPricer",
    "IndexConventions",
    "IndexFixing",
    "IndexFixingStore",
    "IndexSource",
    "InterestRateSwap",
    "LockoutDays",
    "LookbackDays",
    "ObservationShiftType",
    "Ois",
    "OptionType",
    "OvernightCompounding",
    "OvernightIndexedSwap",
    "PayReceive",
    "PublicationTime",
    "SameCurrencyBasisSwap",
    "ScheduleDefinition",
    "ShiftType",
    "SwapPricer",
    "SwapPricingResult",
    "SwapQuote",
    "Swaption",
    "cheapest_to_deliver",
    "conversion_factor",
    "invoice_amount",
    "key_rate_risk",
    "swap_dv01",
]
