"""Bond contract definitions, builders, and shared product-side helpers.

This package exposes the public bond model layer, including fixed-rate,
floating-rate, callable, sinking-fund, inflation-linked, and zero-coupon bond
implementations together with the cash-flow and settlement helpers they use.
"""

from __future__ import annotations

from .cashflows import (
    AccruedInterestCalculator,
    AccruedInterestInputs,
    CashFlowGenerator,
    Schedule,
    ScheduleConfig,
    SettlementCalculator,
)
from fuggers_py.reference.bonds.errors import (
    BondError,
    BondPricingError,
    IdentifierError,
    InvalidBondSpec,
    InvalidIdentifier,
    MissingRequiredField,
    ScheduleError,
    SettlementError,
    YieldConvergenceFailed,
)
from .instruments import (
    AccelerationOption,
    CallEntry,
    CallSchedule,
    CallType,
    CallableBond,
    CallableBondBuilder,
    EmbeddedOptionBond,
    FixedBond,
    FixedBondBuilder,
    FixedRateBond,
    FixedRateBondBuilder,
    FloatingRateNote,
    FloatingRateNoteBuilder,
    SinkingFundBond,
    SinkingFundBondBuilder,
    SinkingFundEntry,
    SinkingFundPayment,
    SinkingFundSchedule,
    TipsBond,
    ZeroCouponBond,
)
from .traits import (
    AmortizingBond,
    Bond,
    BondAnalytics,
    BondCashFlow,
    CashFlowType,
    FixedCouponBond,
    FloatingCouponBond,
    InflationLinkedBond,
)

__all__ = [
    "AccruedInterestCalculator",
    "AccruedInterestInputs",
    "AccelerationOption",
    "AmortizingBond",
    "Bond",
    "BondAnalytics",
    "BondCashFlow",
    "BondError",
    "BondPricingError",
    "CashFlowGenerator",
    "CashFlowType",
    "CallEntry",
    "CallSchedule",
    "CallType",
    "CallableBond",
    "CallableBondBuilder",
    "EmbeddedOptionBond",
    "FixedBond",
    "FixedBondBuilder",
    "FixedCouponBond",
    "FixedRateBond",
    "FixedRateBondBuilder",
    "FloatingCouponBond",
    "FloatingRateNote",
    "FloatingRateNoteBuilder",
    "IdentifierError",
    "InflationLinkedBond",
    "InvalidBondSpec",
    "InvalidIdentifier",
    "MissingRequiredField",
    "Schedule",
    "ScheduleConfig",
    "ScheduleError",
    "SettlementCalculator",
    "SettlementError",
    "SinkingFundBond",
    "SinkingFundBondBuilder",
    "SinkingFundEntry",
    "SinkingFundPayment",
    "SinkingFundSchedule",
    "TipsBond",
    "YieldConvergenceFailed",
    "ZeroCouponBond",
]
